POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "test6",
    "email": "testesheshom@gmail.com",
    "password": "12345678906",
    "confirmPassword": "12345678906"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "ehsan",
    "password": "ehsunhaq86",
    "rememberMe" : true
}
###
PATCH http://localhost:3000/follow/test6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVoc2FuIiwiZW1haWwiOiJlaHN1bmhhZ2g4NkBnbWFpbC5jb20iLCJpYXQiOjE3MjQzMzA5ODEsImV4cCI6MTcyNjkyMjk4MX0.YcXHfXCboelG4gTKJEj3XXXpCNDp89OsnlXorOTaxFo

###
PATCH http://localhost:3000/unfollow/ehsan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFtbWFkMTIiLCJlbWFpbCI6Im0ua2hhemFlZS5wMTJAZ21haWwuY29tIiwiaWF0IjoxNzI0MjI2ODE3LCJleHAiOjE3MjY4MTg4MTd9.3cMYXipPgatqlQvB4uNvsPO_C8XDVO14EaSt2C5QH0U

###
GET http://localhost:3000/ehsan/followers?p=1&c=2

###
GET http://localhost:3000/ehsan/followings?p=1&c=4

###
GET http://localhost:3000/ehsan


# Authorization: f4fa59bc - 290f - 417a - 8968 - 83ba5ee9c25c